Develop
lecrank/bashnya pull request #1
Opened 2023-04-03 20:55 UTC by lecrank

2023-04-05 14:34 UTC, Yu-Leo requested changes
Это первичное ревью. В рамках него я обращаю внимание только на общие моменты (а так же на то, за что глаз зацепится :) ), не углубляясь в детали реализации и работоспособность кода.

1. Молодец, что разбил на модули - это правильно. Однако в данном случае разбиение не совсем информативное. Рекомендую следующее:
    -  Вынести файл `uniq.go` в корень репозитория, чтобы было понятно, что именно он главный (в нём описана ф-ция main)
    - Разбить на модули ещё больше: разделить операции чтения, записи и парсинга флагов на разные пакеты
2. Круто, что сразу написал unit-тесты! Надеюсь, разберешься, почему они не работают. Если нет, пиши.
3. Должен быть только один `go.mod` и один `go.sum` на проект (в корне репозитория)
4. В целом стиль кода хороший, названия переменных и функций понятные, хорошо, что есть комментарии.
5. Прописал замечания в комментариях.

2023-04-05 14:34 UTC, Yu-Leo commented on unique/unique.go
> +func stringsAreEqual(str1, str2 string, f, s int, ignore_reg bool) bool {
Очень большая функция. Декомпозируй на несколько небольших

2023-04-05 14:34 UTC, Yu-Leo commented on unique/unique.go
> +func pickLines(data map[string]int, index_map map[int]string, c, d, u bool) []string {
Довольно большая функция, лучше декомпозировать

2023-04-05 14:34 UTC, Yu-Leo commented on util/uniq.go
> +func main() {
Довольно большая функция. Лучше декомпозировать на несколько небольших

2023-04-07 10:23 UTC, lecrank commented
ИСПРАВЛЕНО

2023-04-08 11:45 UTC, Yu-Leo requested changes
**Первичное ревью пройдено.**

Работоспособность решения не проверяю - для этого есть unit-тесты.
Замечания касаются оформления кода

2023-04-08 11:45 UTC, Yu-Leo commented on parse/file_parser.go
> +		if len(files) == 2 {
Можно сократить до одной строчки:
```go
} else if len(files) == 2 {
```
Читаемость кода повысится

2023-04-08 11:45 UTC, Yu-Leo commented on parse/file_parser.go
> +	filestruct.OutputFile = outputFile
Можно сразу присваивать в поле структуры:
```go
filestruct.InputFile = files[0]
```

2023-04-08 11:45 UTC, Yu-Leo commented on parse/flag_parser.go
> +	IutputFile string // output file name
Если есть структура `Files`, зачем тут эти поля? Их лучше удалить, чтобы структура содержала только значения флагов

2023-04-08 11:45 UTC, Yu-Leo commented on read_data/read_data.go
> +	return lines
1. Лучше использовать `bufio.NewScanner(rd)` и читать при помощи:
```go
for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
```
2. В Go ошибки принято возвращать последним значением из функции. В данном случае её нужно будет "прокинуть" до main и залогировать там. Аналогично проверь по всему коду

То есть, условно `main.go`:
```go
lines, err := readLines()
if err != nil {
    log.Fatalf("%v", err)
}
```

2023-04-08 11:45 UTC, Yu-Leo commented on uniq.go
> +	files.Fill()
1. `Options` и `Files` - схожие по смыслу структуры. Методы их заполнения лучше назвать в одном стиле.
2. И в целом, тут скорее лучше будет не создавать объект структуры и потом его заполнять, а сразу возвращать заполенный объект структуры из функции-парсера

2023-04-08 11:45 UTC, Yu-Leo commented on unique/compare.go
> +func stringsAreEqual(str1, str2 string, f, s int, ignore_reg bool) bool {
Если ты создал структуру опций (флагов), используй её. Не нужно передавать каждый флаг отдельно

2023-04-08 11:45 UTC, Yu-Leo commented on unique/compare.go
> +	}
Выглядит как дублирование кода с изменением только имени переменной. Нужно вынести в функцию

2023-04-08 11:45 UTC, Yu-Leo commented on unique/select.go
> +func fillMap(lines map[string]int, text []string, f, s int, i bool) map[int]string {
Если ты создал структуру опций (флагов), используй её. Не нужно передавать каждый флаг отдельно

2023-04-08 11:45 UTC, Yu-Leo commented on unique/select.go
> +func pickLines(data map[string]int, indexMap map[int]string, c, d, u bool) []string {
Если ты создал структуру опций (флагов), используй её. Не нужно передавать каждый флаг отдельно

2023-04-08 11:45 UTC, Yu-Leo commented on unique/select.go
> +	}
Лучше сделать через else-if

2023-04-08 11:45 UTC, Yu-Leo commented on write_data/write_data.go
> +}
1. Можно по-умолчанию инициализировать `writer` как `os.Stdout` (как у тебя сделано с reader-ом)
2. Никаких доп. `Println` не нужно. Выводы на консоль и в файл должны быть аналогичными

2023-04-10 18:31 UTC, lecrank commented
ИСПРАВЛЕНО (2)

2023-04-17 20:38 UTC, Yu-Leo requested changes
**В целом всё хорошо.**

Замечания по оформлениею прописал в комментариях. 
Поправь их, скинь ещё раз на ревью, и потом будем уже мерджить ветки, скорее всего.

Работоспособность кода не проверяю - вижу, есть unit-тесты.

2023-04-17 20:38 UTC, Yu-Leo commented on parse/file_parser.go
> +}
1. Такого рода "конструкторы" в Go обычно именуются `New<имяСтруктуры>` (то есть `NewFiles`). 
2. Принято возвращать указатель на созданный объект, а не его копию

2023-04-17 20:38 UTC, Yu-Leo commented on parse/flag_parser.go
> +		log.Fatal("Wrong usage!\n\nCorrect: uniq [-c | -d | -u] [-i] [-f num] [-s chars] [input_file [output_file]]")
В Go ошибки принято "прокидывать" до main и логировать там. Возврашай из этой функции ошибку (`error`)

2023-04-17 20:38 UTC, Yu-Leo commented on parse/flag_parser.go
> +func (opt *Options) ParseOptions(c, d, u bool, f, s int, i bool) {
Если эта функция используется только в рамках данного пакета (не вызывается извне), её лучше сделать приватной (имя с маленькой буквы)

2023-04-17 20:38 UTC, Yu-Leo commented on read_data/read_data.go
> +}
Зачем? Используй `io.Reader`

2023-04-17 20:38 UTC, Yu-Leo commented on read_data/read_data.go
> +}
Как-то намудрил. Используй `io.Reader` и передавай в функцию чтения его, а не имя файла

2023-04-17 20:38 UTC, Yu-Leo commented on unique/compare.go
> +func stringsAreEqual(str1, str2 string, f, s int, ignore_reg bool) bool {
Не исправил

2023-04-17 20:38 UTC, Yu-Leo commented on write_data/write_data.go
> +}
Зачем? Используй `io.Writer`

2023-04-17 20:38 UTC, Yu-Leo commented on write_data/write_data.go
> +}
Как-то намудрил. Используй `io.Writer` и передавай в функцию вывода его, а не имя файла

2023-04-18 20:39 UTC, lecrank commented on write_data/write_data.go
> +}
Насчет io.Reader и io.Writer. Когда мы затрагивали тему интерфейсов, Артем сказал создать свои интерфейсы для Reader'a и Writer'a в этой домашке. Поэтому я так и вынес.

2023-04-19 08:21 UTC, Yu-Leo commented on write_data/write_data.go
> +}
Мы с ним обсудили этот момент и пришли к выводу, что в данном случае нет необходимости создавать свои интерфейсы. Лучше использовать стандартные

2023-04-20 20:18 UTC, lecrank commented
ИСПРАВЛЕНО (3)

2023-04-23 07:56 UTC, Yu-Leo approved these changes
**Принято!**

2023-04-23 11:30 UTC, merged